export interface Fruit{
  id: string
  name: string
  vote: number
}

export const fruitsData: Array<Fruit> = [
  {
    id: '1',
    name: '苹果',
    vote: 12080
  },
  {
    id: '2',
    name: '葡萄',
    vote: 10320
  },
  {
    id: '3',
    name: '西瓜',
    vote: 9801
  },
  {
    id: '4',
    name: '香蕉',
    vote: 8431
  },
  {
    id: '5',
    name: '菠萝',
    vote: 7546
  },

]
export const fruitsData2: Array<Fruit> = [
  {
    id: '1',
    name: '苹果',
    vote: 1280
  },
  {
    id: '2',
    name: '葡萄',
    vote: 1020
  },
  {
    id: '3',
    name: '西瓜',
    vote: 981
  },
  {
    id: '4',
    name: '香蕉',
    vote: 841
  },
  {
    id: '5',
    name: '菠萝',
    vote: 756
  },

]